# Generated by Django 5.1.1 on 2024-09-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ejercicio_noimagen_alter_grupomuscular_noimagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ejercicios', models.ManyToManyField(to='myapp.ejercicio')),
            ],
        ),
    ]
