# Generated by Django 5.1.1 on 2024-09-05 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialEjercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('unidad', models.CharField(choices=[('LBS', 'Libras'), ('MILE', 'Millas')], max_length=4)),
                ('tipo_medida', models.CharField(choices=[('REPS', 'Repeticiones'), ('TIME', 'Tiempo')], max_length=4)),
                ('valor_unidad', models.FloatField()),
                ('valor_tipo_medida', models.FloatField()),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ejercicio')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.template')),
            ],
        ),
    ]
