# Generated by Django 5.1.1 on 2024-09-05 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_historialejercicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tiempo_total', models.DurationField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.template')),
            ],
        ),
        migrations.CreateModel(
            name='EjercicioHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('repeticiones', models.IntegerField()),
                ('tiempo_ejercicio', models.DurationField(blank=True, null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ejercicio')),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejercicios_historial', to='myapp.historial')),
            ],
        ),
        migrations.DeleteModel(
            name='HistorialEjercicio',
        ),
    ]
