# Generated by Django 5.1.1 on 2024-09-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_historial_ejerciciohistorial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejerciciohistorial',
            name='tiempo_ejercicio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='tiempo_total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
